"""Added images to users

Revision ID: f7bfb5b25d2f
Revises: e325187c1eeb
Create Date: 2025-10-04 16:09:10.522187

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f7bfb5b25d2f"
down_revision: str | Sequence[str] | None = "e325187c1eeb"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_images",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("image_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_user_images_user_id_users")),
        sa.PrimaryKeyConstraint("user_id", "image_id", name=op.f("pk_user_images")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_images")
    # ### end Alembic commands ###
