"""Changed to array, trying to use another thing

Revision ID: 55d2439e8bf0
Revises: f7bfb5b25d2f
Create Date: 2025-10-04 21:01:15.537905

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "55d2439e8bf0"
down_revision: str | Sequence[str] | None = "f7bfb5b25d2f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_images")
    op.add_column("users", sa.Column("image_ids", sa.ARRAY(sa.UUID()), server_default="{}", nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "image_ids")
    op.create_table("user_images",
    sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=False),
    sa.Column("image_id", sa.UUID(), autoincrement=False, nullable=False),
    sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), server_default=sa.text("now()"), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_user_images_user_id_users")),
    sa.PrimaryKeyConstraint("user_id", "image_id", name=op.f("pk_user_images"))
    )
    # ### end Alembic commands ###
