"""empty message

Revision ID: 7307e5d7342c
Revises: 2fb25e662e00
Create Date: 2025-11-04 00:39:08.755261

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "7307e5d7342c"
down_revision: str | Sequence[str] | None = "2fb25e662e00"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table("image_comparisons",
    sa.Column("id", sa.UUID(), nullable=False),
    sa.Column("first_image_id", sa.UUID(), nullable=False),
    sa.Column("second_image_id", sa.UUID(), nullable=False),
    sa.Column("scores", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column("different_names", sa.Boolean(), nullable=False),
    sa.Column("different_width", sa.Boolean(), nullable=False),
    sa.Column("different_height", sa.Boolean(), nullable=False),
    sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
    sa.PrimaryKeyConstraint("id", name=op.f("pk_image_comparisons"))
    )
    op.create_index(op.f("ix_image_comparisons_first_image_id"), "image_comparisons", ["first_image_id"], unique=False)
    op.create_index("ix_image_comparisons_image_ids", "image_comparisons", ["first_image_id", "second_image_id"], unique=False)
    op.create_index(op.f("ix_image_comparisons_second_image_id"), "image_comparisons", ["second_image_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_image_comparisons_second_image_id"), table_name="image_comparisons")
    op.drop_index("ix_image_comparisons_image_ids", table_name="image_comparisons")
    op.drop_index(op.f("ix_image_comparisons_first_image_id"), table_name="image_comparisons")
    op.drop_table("image_comparisons")
    # ### end Alembic commands ###
