global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: "Pix Erase"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "api"
    scrape_interval: 30s
    static_configs:
      - targets: ["pix_erase.api:8080"]