from pix_erase.domain.common.errors.base import DomainError, DomainFieldError


class BadImageSizeError(DomainFieldError): ...


class BadImageNameError(DomainFieldError): ...


class BadImageScaleError(DomainError): ...


class UnknownImageUpscalerError(DomainError): ...


class BadImageUpscaleAlgorithmError(DomainError): ...
